#pragma once

enum TRACE_FRAME_TYPE
{
	TR_INVALID = 0,
	TR_IRQ_ENTER,
	TR_IRQ_EXIT,
	TR_PACKET_DATA_AVAILABLE,
	TR_IN_PACKET_SENT,
	TR_OUT_PACKET_COMPLETE,
	TR_PACKET_RECEIVED,
	TR_DOEPINT_EPNUM,
	TR_DOEPINT,
	TR_SET_NAK,
	TR_CONTROL_SETUP,
	TR_CONTROL_IN,
	TR_CONTROL_OUT,

	TR_DATA_OUT,
	TR_LAST_DATA_OUT,
	TR_STATUS_OUT,

	TR_DATA_IN,
	TR_LAST_DATA_IN,
	TR_STATUS_IN,

	TR_GENERIC,
};

void log_trace_frame(enum TRACE_FRAME_TYPE type, uint32_t data);

